interface ImportMeta {
	readonly env: {
		VITE_ADMIN_FB_AUTH_EMULATOR_URL: string;
		VITE_ADMIN_FB_FIRESTORE_EMULATOR_HOST: string;
		VITE_ADMIN_FB_FIRESTORE_EMULATOR_PORT: string;
		VITE_ADMIN_FB_STORAGE_EMULATOR_HOST: string;
		VITE_ADMIN_FB_STORAGE_EMULATOR_PORT: string;
		VITE_FB_FUNCTIONS_EMULATOR_HOST: string;
		VITE_FB_FUNCTIONS_EMULATOR_PORT: string;
		VITE_ADMIN_ALGOLIA_APPLICATION_ID: string;
		VITE_ADMIN_ALGOLIA_SEARCH_KEY: string;
		VITE_ADMIN_FB_API_KEY: string;
		VITE_ADMIN_FB_AUTH_DOMAIN: string;
		VITE_ADMIN_FB_DATABASE_URL: string;
		VITE_ADMIN_FB_PROJECT_ID: string;
		VITE_ADMIN_FB_STORAGE_BUCKET: string;
		VITE_ADMIN_FB_MESSAGING_SENDER_ID: string;
		VITE_ADMIN_FB_MEASUREMENT_ID: string;
	};
}
