// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options_staging.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCqTdJShArf7g6X5IhOgkl7u544E5zfrAE',
    appId: '1:51495651779:android:08ef862a962bc041185576',
    messagingSenderId: '51495651779',
    projectId: 'social-income-staging',
    storageBucket: 'social-income-staging.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAulbY2rmZhf8jjeaZkPSpAwaHNHVZ5lhI',
    appId: '1:51495651779:ios:d4d28e75065983fb185576',
    messagingSenderId: '51495651779',
    projectId: 'social-income-staging',
    storageBucket: 'social-income-staging.appspot.com',
    androidClientId: '51495651779-esk1gdivait81filmepqp52t178pul9f.apps.googleusercontent.com',
    iosClientId: '51495651779-tge57s75sh38pcd76g03lpfc1prv8rvd.apps.googleusercontent.com',
    iosBundleId: 'org.socialincome.app.stage',
  );
}
