-- AlterTable
ALTER TABLE "campaign" DROP COLUMN "link_website",
DROP COLUMN "link_instagram",
DROP COLUMN "link_tiktok",
DROP COLUMN "link_facebook",
DROP COLUMN "link_x",
DROP COLUMN "creator_email",
DROP COLUMN "title",
DROP COLUMN "description",
DROP COLUMN "second_description_title",
DROP COLUMN "second_description",
DROP COLUMN "third_description_title",
DROP COLUMN "third_description",
DROP COLUMN "metadata_description",
DROP COLUMN "metadata_og_image",
DROP COLUMN "metadata_twitter_image",
DROP COLUMN "creator_name";
