export const COLORS = [
	'primary',
	'primary-focus',
	'primary-content',
	'secondary',
	'secondary-focus',
	'secondary-content',
	'accent',
	'accent-focus',
	'accent-content',
	'neutral',
	'neutral-focus',
	'neutral-content',
	'base-100',
	'base-200',
	'base-300',
	'base-content',
	'info',
	'info-focus',
	'info-content',
	'success',
	'success-focus',
	'success-content',
	'warning',
	'warning-focus',
	'warning-content',
	'error',
	'error-focus',
	'error-content',
] as const;
export type Color = (typeof COLORS)[number];
