import { campaignSubmissionConfig } from '@/lib/campaign-submission';
import { campaignSubmissionErrorCodes, type CampaignSubmissionErrorCode } from '@/modules/campaigns/campaign.types';
import { type useTranslations } from 'next-intl';
import type { SubmissionLabels } from './campaign-submission/types';

export const buildCampaignSubmissionLabels = (t: ReturnType<typeof useTranslations<'website-common'>>): SubmissionLabels => {
	const errorContext = {
		minDays: campaignSubmissionConfig.minCampaignDurationDays,
		maxDays: campaignSubmissionConfig.maxCampaignDurationDays,
		maxImageMb: campaignSubmissionConfig.maxImageBytes / (1024 * 1024),
	};
	const submissionErrors = Object.fromEntries(
		campaignSubmissionErrorCodes.map((code) => [code, t(`campaigns-page.submission.errors.${code}`, errorContext)]),
	) as Record<CampaignSubmissionErrorCode, string>;

	return {
		programStepTitle: t('campaigns-page.submission.program-step-title'),
		detailsStepTitle: t('campaigns-page.submission.details-step-title'),
		aboutStepTitle: t('campaigns-page.submission.about-step-title'),
		aboutStepSubtitle: t('campaigns-page.submission.about-step-subtitle'),
		aboutStepDescription: t('campaigns-page.submission.about-step-description'),
		personalStepTitle: t('campaigns-page.submission.personal-step-title'),
		personalStepSubtitle: t('campaigns-page.submission.personal-step-subtitle'),
		firstName: t('campaigns-page.submission.first-name'),
		lastName: t('campaigns-page.submission.last-name'),
		email: t('campaigns-page.submission.email'),
		title: t('campaigns-page.submission.title'),
		description: t('campaigns-page.submission.description'),
		goal: t('campaigns-page.submission.goal'),
		setGoalAmount: t('campaigns-page.submission.set-goal-amount'),
		currency: t('campaigns-page.submission.currency'),
		endDate: t('campaigns-page.submission.end-date'),
		duration: t('campaigns-page.submission.duration'),
		duration30: t('campaigns-page.submission.duration-30'),
		duration90: t('campaigns-page.submission.duration-90'),
		duration365: t('campaigns-page.submission.duration-365'),
		durationOther: t('campaigns-page.submission.duration-other'),
		access: t('campaigns-page.submission.access'),
		accessPublic: t('campaigns-page.submission.access-public'),
		accessPublicDescription: t('campaigns-page.submission.access-public-description'),
		accessPrivate: t('campaigns-page.submission.access-private'),
		accessPrivateDescription: t('campaigns-page.submission.access-private-description'),
		accessRecommended: t('campaigns-page.submission.access-recommended'),
		program: t('campaigns-page.submission.program'),
		campaignBackground: t('campaigns-page.submission.campaign-background'),
		uploadImage: t('campaigns-page.submission.upload-image'),
		removeUploadedImage: t('campaigns-page.submission.remove-uploaded-image'),
		profilePicture: t('campaigns-page.submission.profile-picture'),
		profilePictureHint: t('campaigns-page.submission.profile-picture-hint'),
		editProfilePicture: t('campaigns-page.submission.edit-profile-picture'),
		creatorNamePlaceholder: t('campaigns-page.submission.creator-name-placeholder'),
		quote: t('campaigns-page.submission.quote'),
		quotePlaceholder: t('campaigns-page.submission.quote-placeholder'),
		quoteHint: t('campaigns-page.submission.quote-hint'),
		hasAdditionalInformation: t('campaigns-page.submission.has-additional-information'),
		sectionDescription: t('campaigns-page.submission.section-description'),
		sectionImage: t('campaigns-page.submission.section-image'),
		instagramHandle: t('campaigns-page.submission.instagram-handle'),
		xHandle: t('campaigns-page.submission.x-handle'),
		linkWebsite: t('campaigns-page.submission.link-website'),
		tiktokHandle: t('campaigns-page.submission.tiktok-handle'),
		instagramHandlePlaceholder: t('campaigns-page.submission.instagram-handle-placeholder'),
		xHandlePlaceholder: t('campaigns-page.submission.x-handle-placeholder'),
		tiktokHandlePlaceholder: t('campaigns-page.submission.tiktok-handle-placeholder'),
		submit: t('campaigns-page.submission.submit'),
		submitting: t('campaigns-page.submission.submitting'),
		successThankYou: t('campaigns-page.submission.success-thank-you'),
		successCreatedTitle: t('campaigns-page.submission.success-created-title'),
		successLiveTitle: t('campaigns-page.submission.success-live-title'),
		successDidntGetIt: t('campaigns-page.submission.success-didnt-get-it'),
		successRetry: t('campaigns-page.submission.success-retry'),
		successRetrySending: t('campaigns-page.submission.success-retry-sending'),
		successSupportPrefix: t('campaigns-page.submission.success-support-prefix'),
		error: t('campaigns-page.submission.error'),
		currencyPlaceholder: t('campaigns-page.submission.currency-placeholder'),
		imageHint: t('campaigns-page.submission.image-hint'),
		imageFocusHint: t('campaigns-page.submission.image-focus-hint'),
		continue: t('campaigns-page.submission.continue'),
		back: t('campaigns-page.submission.back'),
		allCountries: t('campaigns-page.submission.all-countries'),
		filterByCountry: t('campaigns-page.submission.filter-by-country'),
		formSteps: t('campaigns-page.submission.form-steps'),
		details: t('campaigns-page.submission.details'),
		about: t('campaigns-page.submission.about'),
		personal: t('campaigns-page.submission.personal'),
		programsLoading: t('campaigns-page.submission.programs-loading'),
		programsEmpty: t('campaigns-page.submission.programs-empty'),
		defaultImagesLoading: t('campaigns-page.submission.default-images-loading'),
		defaultImagesError: t('campaigns-page.submission.default-images-error'),
		errors: submissionErrors,
	};
};
