export const STRIPE_API_READ_KEY = process.env.STRIPE_API_READ_KEY!;
export const STRIPE_WEBHOOK_SECRET = process.env.STRIPE_WEBHOOK_SECRET!;

export const POSTFINANCE_EMAIL_USER = process.env.POSTFINANCE_EMAIL_USER!;
export const POSTFINANCE_EMAIL_PASSWORD = process.env.POSTFINANCE_EMAIL_PASSWORD!;

export const NOTIFICATION_EMAIL_USER = process.env.NOTIFICATION_EMAIL_USER!;
export const NOTIFICATION_EMAIL_PASSWORD = process.env.NOTIFICATION_EMAIL_PASSWORD!;

export const TWILIO_SENDER_PHONE = process.env.TWILIO_SENDER_PHONE!;
export const CLOUD_FUNCTIONS_URL = process.env.CLOUD_FUNCTIONS_URL!;

export const TWILIO_SID = process.env.TWILIO_SID!;
export const TWILIO_TOKEN = process.env.TWILIO_TOKEN!;