name: "🐞 Bug Report: UI library/Design System"
description: Create a report to help us improve our design system or UI library
title: ""[UI / Design Bug]: <title>""
labels: ["🐞 Bug", "ui"]
body:
  - type: markdown
    attributes:
      value: |
        # Thank you for taking the time to help us improve the app!
  - type: checkboxes
    attributes:
      label: Is there an existing issue for this?
      description: Please search to see if an issue already exists for the bug you encountered.
      options:
        - label: I have searched the existing issues
          required: true
  - type: textarea
    attributes:
      label: Describe the bug
      description: A clear and concise description of what the bug is.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Steps To Reproduce
      description: Steps to reproduce the behavior.
      placeholder: |
        1. Go to https://socialincome-san.github.io/public/
        2. Click on '....'
        3. Scroll down to '....'
        4. See error
    validations:
      required: false
  - type: textarea
    attributes:
      label: Expected Behavior
      description: A concise description of what you expected to happen.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Screenshots?
      description: |
        If applicable, add screenshots to help explain your problem.

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: textarea
    attributes:
      label: Desktop Environment (please complete the following information)
      description: |
        examples:
          - **OS**: Windows 11
          - **Browser**: Chrome
          - **Version**: 110.111.12.12
      value: |
        - OS:
        - Browser:
        - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Smartphone Type (please complete the following information)
      description: |
        examples:
          - **Device**: iPhone 11
          - **OS**: iOS 13.1
          - **Browser**: Safari
          - **Version**: 22
      value: |
        - Device:
        - OS:
        - Browser:
        - Version:
      render: markdown
    validations:
      required: false
  - type: textarea
    attributes:
      label: Additional context
      description: |
        Links? References? Anything that will give us more context about the issue you are encountering!

        Tip: You can attach images or log files by clicking this area to highlight it and then dragging files in.
    validations:
      required: false
  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our [Code of Conduct](https://github.com/socialincome-san/public/blob/main/CODE_OF_CONDUCT.md)
      options:
        - label: I've read the Code of Conduct and understand my responsibilities as a member of the Social Income community
          required: true
