import "package:app/data/services/auth_service.dart";
import "package:app/l10n/arb/app_localizations.dart";
import "package:cloud_functions/cloud_functions.dart";
import "package:firebase_auth/firebase_auth.dart";

String localizeExceptionMessage(Exception? ex, AppLocalizations localizations) {
  if (ex is FirebaseFunctionsException) {
    return switch (ex.code) {
      "permission-denied" => localizations.invalidVerificationCodeError,
      "invalid-argument" => localizations.argumentError,
      "failed-precondition" => localizations.appNotAuthorized,
      "not-found" => localizations.codeExpired,
      "internal" => localizations.internalError,
      _ => ex.toString(),
    };
  }

  if (ex is FirebaseAuthException) {
    return switch (ex.code) {
      "invalid-verification-code" => localizations.invalidVerificationCodeError,
      "invalid-phone-number" => localizations.invalidPhoneNumberError,
      "invalid-credential" => localizations.invalidCredentialError,
      "user-disabled" => localizations.userDisabledError,
      "admin-only-operation" => localizations.adminOnlyOperation,
      "argument-error" => localizations.argumentError,
      "app-not-authorized" => localizations.appNotAuthorized,
      "app-not-installed" => localizations.appNotInstalled,
      "captcha-check-failed" => localizations.captchaCheckFailed,
      "code-expired" => localizations.codeExpired,
      "cordova-not-ready" => localizations.cordovaNotReady,
      "cors-unsupported" => localizations.corsUnsupported,
      "credential-already-in-use" => localizations.credentialAlreadyInUse,
      "credential-mismatch" => localizations.credentialMismatch,
      "credential-too-old-login-again" => localizations.credentialTooOldLoginAgain,
      "dependent-sdk-init-before-auth" => localizations.dependentSdkInitBeforeAuth,
      "dynamic-link-not-activated" => localizations.dynamicLinkNotActivated,
      "email-change-needs-verification" => localizations.emailChangeNeedsVerification,
      "email-exists" => localizations.emailExists,
      "emulator-config-failed" => localizations.emulatorConfigFailed,
      "expired-oob-code" => localizations.expiredOobCode,
      "expired-popup-request" => localizations.expiredPopupRequest,
      "internal-error" => localizations.internalError,
      "invalid-api-key" => localizations.invalidApiKey,
      "invalid-app-credential" => localizations.invalidAppCredential,
      "invalid-app-id" => localizations.invalidAppId,
      "invalid-auth" => localizations.invalidAuth,
      "invalid-auth-event" => localizations.invalidAuthEvent,
      "invalid-cert-hash" => localizations.invalidCertHash,
      "invalid-code" => localizations.invalidCode,
      "invalid-continue-uri" => localizations.invalidContinueUri,
      "invalid-cordova-configuration" => localizations.invalidCordovaConfiguration,
      "invalid-custom-token" => localizations.invalidCustomToken,
      "invalid-dynamic-link-domain" => localizations.invalidDynamicLinkDomain,
      "invalid-email" => localizations.invalidEmail,
      "invalid-emulator-scheme" => localizations.invalidEmulatorScheme,
      "invalid-idp-response" => localizations.invalidIdpResponse,
      "invalid-message-payload" => localizations.invalidMessagePayload,
      "invalid-mfa-session" => localizations.invalidMfaSession,
      "invalid-oauth-client-id" => localizations.invalidOauthClientId,
      "invalid-oauth-provider" => localizations.invalidOauthProvider,
      "invalid-oob-code" => localizations.invalidOobCode,
      "invalid-origin" => localizations.invalidOrigin,
      "invalid-password" => localizations.invalidPassword,
      "invalid-persistence" => localizations.invalidPersistence,
      "invalid-provider-id" => localizations.invalidProviderId,
      "invalid-recipient-email" => localizations.invalidRecipientEmail,
      "invalid-sender" => localizations.invalidSender,
      "invalid-session-info" => localizations.invalidSessionInfo,
      "invalid-tenant-id" => localizations.invalidTenantId,
      "mfa-info-not-found" => localizations.mfaInfoNotFound,
      "mfa-required" => localizations.mfaRequired,
      "missing-android-package-name" => localizations.missingAndroidPackageName,
      "missing-app-credential" => localizations.missingAppCredential,
      "missing-auth-domain" => localizations.missingAuthDomain,
      "missing-code" => localizations.missingCode,
      "missing-continue-uri" => localizations.missingContinueUri,
      "missing-iframe-start" => localizations.missingIframeStart,
      "missing-ios-bundle-id" => localizations.missingIosBundleId,
      "missing-or-invalid-nonce" => localizations.missingOrInvalidNonce,
      "missing-mfa-info" => localizations.missingMfaInfo,
      "missing-mfa-session" => localizations.missingMfaSession,
      "missing-phone-number" => localizations.missingPhoneNumber,
      "missing-session-info" => localizations.missingSessionInfo,
      "module-destroyed" => localizations.moduleDestroyed,
      "need-confirmation" => localizations.needConfirmation,
      "network-request-failed" => localizations.networkRequestFailed,
      "null-user" => localizations.nullUser,
      "no-auth-event" => localizations.noAuthEvent,
      "no-such-provider" => localizations.noSuchProvider,
      "operation-not-allowed" => localizations.operationNotAllowed,
      "operation-not-supported" => localizations.operationNotSupported,
      "popup-blocked" => localizations.popupBlocked,
      "popup-closed-by-user" => localizations.popupClosedByUser,
      "provider-already-linked" => localizations.providerAlreadyLinked,
      "quota-exceeded" => localizations.quotaExceeded,
      "redirect-cancelled-by-user" => localizations.redirectCancelledByUser,
      "redirect-operation-pending" => localizations.redirectOperationPending,
      "rejected-credential" => localizations.rejectedCredential,
      "second-factor-already-enrolled" => localizations.secondFactorAlreadyEnrolled,
      "second-factor-limit-exceeded" => localizations.secondFactorLimitExceeded,
      "tenant-id-mismatch" => localizations.tenantIdMismatch,
      "timeout" => localizations.timeoutError,
      "token-expired" => localizations.tokenExpired,
      "too-many-attempts-try-later" => localizations.tooManyAttemptsTryLater,
      "unauthorized-domain" => localizations.unauthorizedDomain,
      "unsupported-first-factor" => localizations.unsupportedFirstFactor,
      "unsupported-persistence" => localizations.unsupportedPersistence,
      "unsupported-tenant-operation" => localizations.unsupportedTenantOperation,
      "unverified-email" => localizations.unverifiedEmail,
      "user-cancelled" => localizations.userCancelled,
      "user-deleted" => localizations.userDeleted,
      "user-mismatch" => localizations.userMismatch,
      "user-signed-out" => localizations.userSignedOut,
      "weak-password" => localizations.weakPassword,
      "web-storage-unsupported" => localizations.webStorageUnsupported,
      "already-initialized" => localizations.alreadyInitialized,
      "recaptcha-not-enabled" => localizations.recaptchaNotEnabled,
      "missing-recaptcha-token" => localizations.missingRecaptchaToken,
      "invalid-recaptcha-token" => localizations.invalidRecaptchaToken,
      "invalid-recaptcha-action" => localizations.invalidRecaptchaAction,
      "missing-client-type" => localizations.missingClientType,
      "missing-recaptcha-version" => localizations.missingRecaptchaVersion,
      "invalid-recaptcha-version" => localizations.invalidRecaptchaVersion,
      "invalid-req-type" => localizations.invalidReqType,
      _ => ex.toString(),
    };
  }

  if (ex is AuthException) {
    return switch (ex.code) {
      "failed-sent-verification-code" => localizations.failedSentVerificationCodeError,
      "failed-code-verification" => localizations.failedCodeVerificationCodeError,
      "invalid-verification-code" => localizations.invalidVerificationCodeError,
      "invalid-app-check-token" => localizations.invalidAppCheckTokenError,
      "invalid-phone-number" => localizations.invalidPhoneNumberError,
      _ => ex.toString(),
    };
  }

  return ex.toString();
}
