import type { Currency } from '../../generated/prisma/enums';
import { CountryCode, Currency as CurrencyValues } from '../../generated/prisma/enums';

export type { Currency };

const CURRENCIES = Object.values(CurrencyValues) as Currency[];
export const allCurrencies = CURRENCIES;

const FALLBACK_CURRENCY: Currency = 'USD';
const countryToCurrency = new Map<CountryCode, Currency>([
	['AE', 'AED'],
	['AF', 'AFN'],
	['AD', 'EUR'],
	['AO', 'AOA'],
	['AR', 'ARS'],
	['AL', 'EUR'],
	['AM', 'EUR'],
	['AU', 'AUD'],
	['AZ', 'AZN'],
	['BD', 'BDT'],
	['AT', 'EUR'],
	['BH', 'BHD'],
	['BO', 'BOB'],
	['BA', 'EUR'],
	['BE', 'EUR'],
	['BJ', 'XOF'],
	['BG', 'EUR'],
	['BF', 'XOF'],
	['BI', 'BIF'],
	['BN', 'BND'],
	['BR', 'BRL'],
	['BW', 'BWP'],
	['BY', 'EUR'],
	['BZ', 'BZD'],
	['CA', 'CAD'],
	['CD', 'CDF'],
	['CF', 'XAF'],
	['CG', 'XAF'],
	['CI', 'XOF'],
	['CH', 'CHF'],
	['CL', 'CLP'],
	['CM', 'XAF'],
	['CN', 'CNY'],
	['CO', 'COP'],
	['CR', 'CRC'],
	['CV', 'CVE'],
	['CY', 'EUR'],
	['CZ', 'EUR'],
	['DJ', 'DJF'],
	['DE', 'EUR'],
	['DZ', 'DZD'],
	['DK', 'EUR'],
	['EG', 'EGP'],
	['EE', 'EUR'],
	['ER', 'ERN'],
	['ET', 'ETB'],
	['ES', 'EUR'],
	['FI', 'EUR'],
	['FO', 'EUR'],
	['FR', 'EUR'],
	['GB', 'GBP'],
	['GE', 'EUR'],
	['GH', 'GHS'],
	['GI', 'EUR'],
	['GM', 'GMD'],
	['GN', 'GNF'],
	['GQ', 'XAF'],
	['GT', 'GTQ'],
	['GR', 'EUR'],
	['GW', 'XOF'],
	['GY', 'GYD'],
	['HK', 'HKD'],
	['HR', 'EUR'],
	['HU', 'EUR'],
	['ID', 'IDR'],
	['IE', 'EUR'],
	['IL', 'ILS'],
	['IN', 'INR'],
	['IQ', 'IQD'],
	['IR', 'IRR'],
	['IS', 'EUR'],
	['IT', 'EUR'],
	['JM', 'JMD'],
	['JO', 'JOD'],
	['JP', 'JPY'],
	['KE', 'KES'],
	['KG', 'KGS'],
	['KH', 'KHR'],
	['KM', 'KMF'],
	['KR', 'KRW'],
	['KW', 'KWD'],
	['KZ', 'KZT'],
	['LA', 'LAK'],
	['LB', 'LBP'],
	['LK', 'LKR'],
	['LR', 'LRD'],
	['LS', 'LSL'],
	['LT', 'EUR'],
	['LY', 'LYD'],
	['LU', 'EUR'],
	['LV', 'EUR'],
	['MA', 'MAD'],
	['MD', 'MDL'],
	['MG', 'MGA'],
	['MC', 'EUR'],
	['MK', 'EUR'],
	['ML', 'XOF'],
	['MM', 'MMK'],
	['MN', 'MNT'],
	['MR', 'MRO'],
	['MU', 'MUR'],
	['MW', 'MWK'],
	['MX', 'MXN'],
	['MY', 'MYR'],
	['MZ', 'MZN'],
	['MT', 'EUR'],
	['NA', 'NAD'],
	['NE', 'XOF'],
	['NG', 'NGN'],
	['NI', 'NIO'],
	['NL', 'EUR'],
	['NO', 'NOK'],
	['NP', 'NPR'],
	['NZ', 'NZD'],
	['OM', 'OMR'],
	['PA', 'PAB'],
	['PE', 'PEN'],
	['PG', 'PGK'],
	['PH', 'PHP'],
	['PK', 'PKR'],
	['PL', 'EUR'],
	['PT', 'EUR'],
	['PY', 'PYG'],
	['QA', 'QAR'],
	['RO', 'RON'],
	['RS', 'RSD'],
	['RU', 'RUB'],
	['RW', 'RWF'],
	['SA', 'SAR'],
	['SC', 'SCR'],
	['SD', 'SDG'],
	['SE', 'SEK'],
	['SG', 'SGD'],
	['SL', 'SLE'],
	['SN', 'XOF'],
	['SO', 'SOS'],
	['SS', 'SSP'],
	['ST', 'STD'],
	['SV', 'SVC'],
	['SY', 'SYP'],
	['SZ', 'SZL'],
	['TD', 'XAF'],
	['TG', 'XOF'],
	['TH', 'THB'],
	['TJ', 'TJS'],
	['TM', 'TMT'],
	['TN', 'TND'],
	['TR', 'TRY'],
	['TT', 'TTD'],
	['TW', 'TWD'],
	['TZ', 'TZS'],
	['UA', 'UAH'],
	['UG', 'UGX'],
	['US', 'USD'],
	['UY', 'UYU'],
	['UZ', 'UZS'],
	['VE', 'VES'],
	['VN', 'VND'],
	['YE', 'YER'],
	['ZA', 'ZAR'],
	['ZM', 'ZMW'],
	['ZW', 'ZWL'],
]);

export const bestGuessCurrency = (country: CountryCode | undefined): Currency => {
	// best guess mapping from two-letter country code to a supported currency
	if (!country) {
		return FALLBACK_CURRENCY;
	}
	const currency = countryToCurrency.get(country);
	return currency || FALLBACK_CURRENCY;
};

export const isValidCurrency = (currency: string | undefined): currency is Currency => {
	return CURRENCIES.includes(currency as Currency);
};
