import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('http://localhost:3000/en/int');
  await page.getByRole('navigation').getByRole('link', { name: 'My Account' }).click();
  await page.getByRole('button', { name: 'Back to login' }).click();
  await page.getByRole('textbox', { name: 'Email' }).click();
  await page.getByRole('textbox', { name: 'Email' }).fill('test');
  await page.getByRole('textbox', { name: 'Email' }).press('Alt+@');
  await page.getByRole('textbox', { name: 'Email' }).fill('test@portal.org');
  await page.getByRole('button', { name: 'Send login link' }).click();
  await page.goto('http://localhost:3000/portal');
  await page.getByTestId('create-program-modal-trigger').click();
  await page.getByTestId('radio-card-country-sierra-leone').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByTestId('radio-card-targeted').click();
  await page.getByTestId('pill-multi-select-poverty').click();
  await page.getByTestId('pill-multi-select-health').click();
  await page.getByTestId('pill-multi-select-female').click();
  await page.getByRole('button', { name: 'Continue' }).click();
  await page.getByRole('slider').click();
  await page.getByRole('slider').click();
  await page.locator('.absolute.data-\\[orientation\\=horizontal\\]\\:h-full').click();
  await page.locator('.absolute.data-\\[orientation\\=horizontal\\]\\:h-full').click();
  await page.getByRole('slider').click();
  await page.getByRole('slider').click();
  await page.locator('.absolute.data-\\[orientation\\=horizontal\\]\\:h-full').click();
  await page.getByRole('slider').click();
  await page.getByRole('slider').click();
  await page.locator('.absolute.data-\\[orientation\\=horizontal\\]\\:h-full').click();
  await page.locator('.absolute.data-\\[orientation\\=horizontal\\]\\:h-full').click();
  await page.getByRole('slider').click();
  await page.getByTestId('customize-payouts-switch').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByText('Program duration36 monthsPayout per intervalUSD 32Payout').click();
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').click();
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').click();
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('recipients-slider').getByRole('slider').click();
  await page.getByTestId('recipients-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('program-duration-slider').getByRole('slider').click();
  await page.getByTestId('program-duration-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('program-duration-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('program-duration-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('program-duration-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('program-duration-slider').getByRole('slider').press('ArrowRight');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').click();
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByTestId('payout-per-interval-slider').getByRole('slider').press('ArrowLeft');
  await page.getByText('USD1’517USD 37 / month').click();
  await page.getByText('USD1’517USD 37 / month').click();
});