export type IsoCountry = {
	name: string;
	isoCode: string;
};

export const isoCountries: IsoCountry[] = [
	{ name: 'Afghanistan', isoCode: 'AFG' },
	{ name: 'Åland Islands', isoCode: 'ALA' },
	{ name: 'Albania', isoCode: 'ALB' },
	{ name: 'Algeria', isoCode: 'DZA' },
	{ name: 'American Samoa', isoCode: 'ASM' },
	{ name: 'Andorra', isoCode: 'AND' },
	{ name: 'Angola', isoCode: 'AGO' },
	{ name: 'Anguilla', isoCode: 'AIA' },
	{ name: 'Antarctica', isoCode: 'ATA' },
	{ name: 'Antigua and Barbuda', isoCode: 'ATG' },
	{ name: 'Argentina', isoCode: 'ARG' },
	{ name: 'Armenia', isoCode: 'ARM' },
	{ name: 'Aruba', isoCode: 'ABW' },
	{ name: 'Australia', isoCode: 'AUS' },
	{ name: 'Austria', isoCode: 'AUT' },
	{ name: 'Azerbaijan', isoCode: 'AZE' },
	{ name: 'Bahamas', isoCode: 'BHS' },
	{ name: 'Bahrain', isoCode: 'BHR' },
	{ name: 'Bangladesh', isoCode: 'BGD' },
	{ name: 'Barbados', isoCode: 'BRB' },
	{ name: 'Belarus', isoCode: 'BLR' },
	{ name: 'Belgium', isoCode: 'BEL' },
	{ name: 'Belize', isoCode: 'BLZ' },
	{ name: 'Benin', isoCode: 'BEN' },
	{ name: 'Bermuda', isoCode: 'BMU' },
	{ name: 'Bhutan', isoCode: 'BTN' },
	{ name: 'Bolivia, Plurinational State of', isoCode: 'BOL' },
	{ name: 'Bonaire, Sint Eustatius and Saba', isoCode: 'BES' },
	{ name: 'Bosnia and Herzegovina', isoCode: 'BIH' },
	{ name: 'Botswana', isoCode: 'BWA' },
	{ name: 'Bouvet Island', isoCode: 'BVT' },
	{ name: 'Brazil', isoCode: 'BRA' },
	{ name: 'British Indian Ocean Territory', isoCode: 'IOT' },
	{ name: 'Brunei Darussalam', isoCode: 'BRN' },
	{ name: 'Bulgaria', isoCode: 'BGR' },
	{ name: 'Burkina Faso', isoCode: 'BFA' },
	{ name: 'Burundi', isoCode: 'BDI' },
	{ name: 'Cabo Verde', isoCode: 'CPV' },
	{ name: 'Cambodia', isoCode: 'KHM' },
	{ name: 'Cameroon', isoCode: 'CMR' },
	{ name: 'Canada', isoCode: 'CAN' },
	{ name: 'Cayman Islands', isoCode: 'CYM' },
	{ name: 'Central African Republic', isoCode: 'CAF' },
	{ name: 'Chad', isoCode: 'TCD' },
	{ name: 'Chile', isoCode: 'CHL' },
	{ name: 'China', isoCode: 'CHN' },
	{ name: 'Christmas Island', isoCode: 'CXR' },
	{ name: 'Cocos (Keeling) Islands', isoCode: 'CCK' },
	{ name: 'Colombia', isoCode: 'COL' },
	{ name: 'Comoros', isoCode: 'COM' },
	{ name: 'Congo', isoCode: 'COG' },
	{ name: 'Congo, Democratic Republic of the', isoCode: 'COD' },
	{ name: 'Cook Islands', isoCode: 'COK' },
	{ name: 'Costa Rica', isoCode: 'CRI' },
	{ name: "Côte d'Ivoire", isoCode: 'CIV' },
	{ name: 'Croatia', isoCode: 'HRV' },
	{ name: 'Cuba', isoCode: 'CUB' },
	{ name: 'Curaçao', isoCode: 'CUW' },
	{ name: 'Cyprus', isoCode: 'CYP' },
	{ name: 'Czechia', isoCode: 'CZE' },
	{ name: 'Denmark', isoCode: 'DNK' },
	{ name: 'Djibouti', isoCode: 'DJI' },
	{ name: 'Dominica', isoCode: 'DMA' },
	{ name: 'Dominican Republic', isoCode: 'DOM' },
	{ name: 'Ecuador', isoCode: 'ECU' },
	{ name: 'Egypt', isoCode: 'EGY' },
	{ name: 'El Salvador', isoCode: 'SLV' },
	{ name: 'Equatorial Guinea', isoCode: 'GNQ' },
	{ name: 'Eritrea', isoCode: 'ERI' },
	{ name: 'Estonia', isoCode: 'EST' },
	{ name: 'Eswatini', isoCode: 'SWZ' },
	{ name: 'Ethiopia', isoCode: 'ETH' },
	{ name: 'Falkland Islands (Malvinas)', isoCode: 'FLK' },
	{ name: 'Faroe Islands', isoCode: 'FRO' },
	{ name: 'Fiji', isoCode: 'FJI' },
	{ name: 'Finland', isoCode: 'FIN' },
	{ name: 'France', isoCode: 'FRA' },
	{ name: 'French Guiana', isoCode: 'GUF' },
	{ name: 'French Polynesia', isoCode: 'PYF' },
	{ name: 'French Southern Territories', isoCode: 'ATF' },
	{ name: 'Gabon', isoCode: 'GAB' },
	{ name: 'Gambia', isoCode: 'GMB' },
	{ name: 'Georgia', isoCode: 'GEO' },
	{ name: 'Germany', isoCode: 'DEU' },
	{ name: 'Ghana', isoCode: 'GHA' },
	{ name: 'Gibraltar', isoCode: 'GIB' },
	{ name: 'Greece', isoCode: 'GRC' },
	{ name: 'Greenland', isoCode: 'GRL' },
	{ name: 'Grenada', isoCode: 'GRD' },
	{ name: 'Guadeloupe', isoCode: 'GLP' },
	{ name: 'Guam', isoCode: 'GUM' },
	{ name: 'Guatemala', isoCode: 'GTM' },
	{ name: 'Guernsey', isoCode: 'GGY' },
	{ name: 'Guinea', isoCode: 'GIN' },
	{ name: 'Guinea-Bissau', isoCode: 'GNB' },
	{ name: 'Guyana', isoCode: 'GUY' },
	{ name: 'Haiti', isoCode: 'HTI' },
	{ name: 'Heard Island and McDonald Islands', isoCode: 'HMD' },
	{ name: 'Holy See', isoCode: 'VAT' },
	{ name: 'Honduras', isoCode: 'HND' },
	{ name: 'Hong Kong', isoCode: 'HKG' },
	{ name: 'Hungary', isoCode: 'HUN' },
	{ name: 'Iceland', isoCode: 'ISL' },
	{ name: 'India', isoCode: 'IND' },
	{ name: 'Indonesia', isoCode: 'IDN' },
	{ name: 'Iran, Islamic Republic of', isoCode: 'IRN' },
	{ name: 'Iraq', isoCode: 'IRQ' },
	{ name: 'Ireland', isoCode: 'IRL' },
	{ name: 'Isle of Man', isoCode: 'IMN' },
	{ name: 'Israel', isoCode: 'ISR' },
	{ name: 'Italy', isoCode: 'ITA' },
	{ name: 'Jamaica', isoCode: 'JAM' },
	{ name: 'Japan', isoCode: 'JPN' },
	{ name: 'Jersey', isoCode: 'JEY' },
	{ name: 'Jordan', isoCode: 'JOR' },
	{ name: 'Kazakhstan', isoCode: 'KAZ' },
	{ name: 'Kenya', isoCode: 'KEN' },
	{ name: 'Kiribati', isoCode: 'KIR' },
	{ name: "Korea, Democratic People's Republic of", isoCode: 'PRK' },
	{ name: 'Korea, Republic of', isoCode: 'KOR' },
	{ name: 'Kuwait', isoCode: 'KWT' },
	{ name: 'Kyrgyzstan', isoCode: 'KGZ' },
	{ name: "Lao People's Democratic Republic", isoCode: 'LAO' },
	{ name: 'Latvia', isoCode: 'LVA' },
	{ name: 'Lebanon', isoCode: 'LBN' },
	{ name: 'Lesotho', isoCode: 'LSO' },
	{ name: 'Liberia', isoCode: 'LBR' },
	{ name: 'Libya', isoCode: 'LBY' },
	{ name: 'Liechtenstein', isoCode: 'LIE' },
	{ name: 'Lithuania', isoCode: 'LTU' },
	{ name: 'Luxembourg', isoCode: 'LUX' },
	{ name: 'Macao', isoCode: 'MAC' },
	{ name: 'Madagascar', isoCode: 'MDG' },
	{ name: 'Malawi', isoCode: 'MWI' },
	{ name: 'Malaysia', isoCode: 'MYS' },
	{ name: 'Maldives', isoCode: 'MDV' },
	{ name: 'Mali', isoCode: 'MLI' },
	{ name: 'Malta', isoCode: 'MLT' },
	{ name: 'Marshall Islands', isoCode: 'MHL' },
	{ name: 'Martinique', isoCode: 'MTQ' },
	{ name: 'Mauritania', isoCode: 'MRT' },
	{ name: 'Mauritius', isoCode: 'MUS' },
	{ name: 'Mayotte', isoCode: 'MYT' },
	{ name: 'Mexico', isoCode: 'MEX' },
	{ name: 'Micronesia, Federated States of', isoCode: 'FSM' },
	{ name: 'Moldova, Republic of', isoCode: 'MDA' },
	{ name: 'Monaco', isoCode: 'MCO' },
	{ name: 'Mongolia', isoCode: 'MNG' },
	{ name: 'Montenegro', isoCode: 'MNE' },
	{ name: 'Montserrat', isoCode: 'MSR' },
	{ name: 'Morocco', isoCode: 'MAR' },
	{ name: 'Mozambique', isoCode: 'MOZ' },
	{ name: 'Myanmar', isoCode: 'MMR' },
	{ name: 'Namibia', isoCode: 'NAM' },
	{ name: 'Nauru', isoCode: 'NRU' },
	{ name: 'Nepal', isoCode: 'NPL' },
	{ name: 'Netherlands, Kingdom of the', isoCode: 'NLD' },
	{ name: 'New Caledonia', isoCode: 'NCL' },
	{ name: 'New Zealand', isoCode: 'NZL' },
	{ name: 'Nicaragua', isoCode: 'NIC' },
	{ name: 'Niger', isoCode: 'NER' },
	{ name: 'Nigeria', isoCode: 'NGA' },
	{ name: 'Niue', isoCode: 'NIU' },
	{ name: 'Norfolk Island', isoCode: 'NFK' },
	{ name: 'North Macedonia', isoCode: 'MKD' },
	{ name: 'Northern Mariana Islands', isoCode: 'MNP' },
	{ name: 'Norway', isoCode: 'NOR' },
	{ name: 'Oman', isoCode: 'OMN' },
	{ name: 'Pakistan', isoCode: 'PAK' },
	{ name: 'Palau', isoCode: 'PLW' },
	{ name: 'Palestine, State of', isoCode: 'PSE' },
	{ name: 'Panama', isoCode: 'PAN' },
	{ name: 'Papua New Guinea', isoCode: 'PNG' },
	{ name: 'Paraguay', isoCode: 'PRY' },
	{ name: 'Peru', isoCode: 'PER' },
	{ name: 'Philippines', isoCode: 'PHL' },
	{ name: 'Pitcairn', isoCode: 'PCN' },
	{ name: 'Poland', isoCode: 'POL' },
	{ name: 'Portugal', isoCode: 'PRT' },
	{ name: 'Puerto Rico', isoCode: 'PRI' },
	{ name: 'Qatar', isoCode: 'QAT' },
	{ name: 'Réunion', isoCode: 'REU' },
	{ name: 'Romania', isoCode: 'ROU' },
	{ name: 'Russian Federation', isoCode: 'RUS' },
	{ name: 'Rwanda', isoCode: 'RWA' },
	{ name: 'Saint Barthélemy', isoCode: 'BLM' },
	{ name: 'Saint Helena, Ascension and Tristan da Cunha', isoCode: 'SHN' },
	{ name: 'Saint Kitts and Nevis', isoCode: 'KNA' },
	{ name: 'Saint Lucia', isoCode: 'LCA' },
	{ name: 'Saint Martin (French part)', isoCode: 'MAF' },
	{ name: 'Saint Pierre and Miquelon', isoCode: 'SPM' },
	{ name: 'Saint Vincent and the Grenadines', isoCode: 'VCT' },
	{ name: 'Samoa', isoCode: 'WSM' },
	{ name: 'San Marino', isoCode: 'SMR' },
	{ name: 'Sao Tome and Principe', isoCode: 'STP' },
	{ name: 'Saudi Arabia', isoCode: 'SAU' },
	{ name: 'Senegal', isoCode: 'SEN' },
	{ name: 'Serbia', isoCode: 'SRB' },
	{ name: 'Seychelles', isoCode: 'SYC' },
	{ name: 'Sierra Leone', isoCode: 'SLE' },
	{ name: 'Singapore', isoCode: 'SGP' },
	{ name: 'Sint Maarten (Dutch part)', isoCode: 'SXM' },
	{ name: 'Slovakia', isoCode: 'SVK' },
	{ name: 'Slovenia', isoCode: 'SVN' },
	{ name: 'Solomon Islands', isoCode: 'SLB' },
	{ name: 'Somalia', isoCode: 'SOM' },
	{ name: 'South Africa', isoCode: 'ZAF' },
	{ name: 'South Georgia and the South Sandwich Islands', isoCode: 'SGS' },
	{ name: 'South Sudan', isoCode: 'SSD' },
	{ name: 'Spain', isoCode: 'ESP' },
	{ name: 'Sri Lanka', isoCode: 'LKA' },
	{ name: 'Sudan', isoCode: 'SDN' },
	{ name: 'Suriname', isoCode: 'SUR' },
	{ name: 'Svalbard and Jan Mayen', isoCode: 'SJM' },
	{ name: 'Sweden', isoCode: 'SWE' },
	{ name: 'Switzerland', isoCode: 'CHE' },
	{ name: 'Syrian Arab Republic', isoCode: 'SYR' },
	{ name: 'Taiwan, Province of China', isoCode: 'TWN' },
	{ name: 'Tajikistan', isoCode: 'TJK' },
	{ name: 'Tanzania, United Republic of', isoCode: 'TZA' },
	{ name: 'Thailand', isoCode: 'THA' },
	{ name: 'Timor-Leste', isoCode: 'TLS' },
	{ name: 'Togo', isoCode: 'TGO' },
	{ name: 'Tokelau', isoCode: 'TKL' },
	{ name: 'Tonga', isoCode: 'TON' },
	{ name: 'Trinidad and Tobago', isoCode: 'TTO' },
	{ name: 'Tunisia', isoCode: 'TUN' },
	{ name: 'Türkiye', isoCode: 'TUR' },
	{ name: 'Turkmenistan', isoCode: 'TKM' },
	{ name: 'Turks and Caicos Islands', isoCode: 'TCA' },
	{ name: 'Tuvalu', isoCode: 'TUV' },
	{ name: 'Uganda', isoCode: 'UGA' },
	{ name: 'Ukraine', isoCode: 'UKR' },
	{ name: 'United Arab Emirates', isoCode: 'ARE' },
	{ name: 'United Kingdom of Great Britain and Northern Ireland', isoCode: 'GBR' },
	{ name: 'United States of America', isoCode: 'USA' },
	{ name: 'United States Minor Outlying Islands', isoCode: 'UMI' },
	{ name: 'Uruguay', isoCode: 'URY' },
	{ name: 'Uzbekistan', isoCode: 'UZB' },
	{ name: 'Vanuatu', isoCode: 'VUT' },
	{ name: 'Venezuela, Bolivarian Republic of', isoCode: 'VEN' },
	{ name: 'Viet Nam', isoCode: 'VNM' },
	{ name: 'Virgin Islands (British)', isoCode: 'VGB' },
	{ name: 'Virgin Islands (U.S.)', isoCode: 'VIR' },
	{ name: 'Wallis and Futuna', isoCode: 'WLF' },
	{ name: 'Western Sahara', isoCode: 'ESH' },
	{ name: 'Yemen', isoCode: 'YEM' },
	{ name: 'Zambia', isoCode: 'ZMB' },
	{ name: 'Zimbabwe', isoCode: 'ZWE' },
];

const isoCountryMap = new Map(isoCountries.map((c) => [c.isoCode, c.name]));

export function getCountryNameByIsoCode(isoCode: string): string {
	return isoCountryMap.get(isoCode) ?? isoCode;
}
