services:
  postgres:
    image: postgres:18-alpine@sha256:9a8afca54e7861fd90fab5fdf4c42477a6b1cb7d293595148e674e0a3181de15
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social-income
      POSTGRES_PASSWORD: social-income
      POSTGRES_DB: social-income
      TZ: "Europe/Zurich"
      PGTZ: "Europe/Zurich"
