services:
  postgres:
    image: postgres:18-alpine@sha256:d3e1620b530c944afa6e887d22eb899824da68e19c52024bf98f5220c88a65b2
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social-income
      POSTGRES_PASSWORD: social-income
      POSTGRES_DB: social-income
      TZ: "Europe/Zurich"
      PGTZ: "Europe/Zurich"
