services:
  postgres:
    image: postgres:18-alpine@sha256:77f585114c32fbca283dc835b0596f4e52b51b4c6662d7810b2f4084f60a1873
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: social-income
      POSTGRES_PASSWORD: social-income
      POSTGRES_DB: social-income
      TZ: "Europe/Zurich"
      PGTZ: "Europe/Zurich"
