import type { KnipConfig } from 'knip';

const config: KnipConfig = {
	ignoreFiles: ['src/lib/database/schema.prisma', 'test/e2e/setup/auth-setup.ts'],
	ignoreDependencies: [
		'react',
		'react-hook-form',
		'zod',
		'@hookform/resolvers',
		'jest',
		'@sendgrid/mail',
		'dotenv-cli',
		'prisma',
		'next-openapi-gen',
		'tsx',
		'storyblok',
		'npm-run-all',
		'@radix-ui/react-accordion',
		'@radix-ui/react-popover',
		'@radix-ui/react-progress',
		'@radix-ui/react-switch',
		'@radix-ui/react-radio-group',
		'@radix-ui/react-slider',
		'@radix-ui/react-tabs',
		'@radix-ui/react-tooltip',
		'@firebase/analytics',
		'@sendgrid/client',
		'@google-cloud/storage',
		'xstate',
		'@xstate/react',
	],
	ignoreBinaries: [
		'tsx',
		'next',
		'firebase',
		'playwright',
		'eslint',
		'next-openapi-gen',
		'tsc',
		'dotenv',
		'prisma',
		'knip',
	],
	ignoreUnresolved: ['dotenv/config'],
};

export default config;
