import type { KnipConfig } from 'knip';

const config: KnipConfig = {
	ignoreFiles: [
		'src/lib/database/schema.prisma',
		'test/e2e/setup/test-setup.ts',
		'test/e2e/setup/utils.ts',
		'src/lib/utils/storyblock-image-loader.ts',
	],
	ignoreDependencies: [
		'react',
		'react-hook-form',
		'zod',
		'@hookform/resolvers',
		'jest',
		'@sendgrid/mail',
		'dotenv-cli',
		'@prisma/client',
		'next-openapi-gen',
		'tsx',
		'dotenv',
		'storyblok',
		'npm-run-all',
		'@radix-ui/react-accordion',
		'@radix-ui/react-popover',
		'@radix-ui/react-progress',
		'@radix-ui/react-switch',
		'@radix-ui/react-radio-group',
		'@radix-ui/react-slider',
		'@radix-ui/react-tabs',
		'@radix-ui/react-tooltip',
		'@radix-ui/react-toggle-group',
		'@firebase/analytics',
		'@sendgrid/client',
		'@google-cloud/storage',
		'@tailwindcss/typography',
		'tailwindcss-animate',
		'xstate',
		'@xstate/react',
	],
	ignoreBinaries: [
		'tsx',
		'next',
		'firebase',
		'playwright',
		'eslint',
		'next-openapi-gen',
		'tsc',
		'dotenv',
		'prisma',
		'knip',
		'npm-run-all',
		'jest',
	],
};

export default config;
