[tools]
node = "24"
java = "23"

[tasks.install]
run = "npm ci"

[tasks.db]
run = "npm run db:up"

[tasks.firebase]
run = "npm run emulator:start"
depends = ["install"]

[tasks.website]
run = "npm run serve"
depends = ["install", "db"]

[tasks.website-ssl]
run = "npm run serve:ssl"
depends = ["install", "db"]

[tasks.storybook]
run = "npm run storybook"
depends = ["install"]

[tasks.dev]
depends = ["firebase", "website", "storybook"]

[tasks.dev-ssl]
depends = ["firebase", "website-ssl", "storybook"]
