import type { NextConfig } from 'next';

type Redirects = Awaited<ReturnType<NonNullable<NextConfig['redirects']>>>;

const redirects: Redirects = [
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/about-us',
		destination: '/:lang/:currency/mission',
		permanent: true,
	},
	{ source: '/about-us', destination: '/en/usd/mission', permanent: true },
	{ source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/app', destination: '/:lang/:currency/mobile-app', permanent: true },
	{ source: '/app', destination: '/en/usd/mobile-app', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/bank',
		destination: '/:lang/:currency/mobile-money',
		permanent: true,
	},
	{ source: '/bank', destination: '/en/usd/mobile-money', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/arts',
		destination: '/:lang/:currency/programs/ubi-for-artists',
		permanent: true,
	},
	{ source: '/arts', destination: '/en/usd/programs/ubi-for-artists', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/books',
		destination: '/:lang/:currency/journal/recommended-reading',
		permanent: true,
	},
	{ source: '/books', destination: '/en/usd/journal/recommended-reading', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/partners',
		destination: '/:lang/:currency/local-partners',
		permanent: true,
	},
	{ source: '/partners', destination: '/en/usd/local-partners', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/partnership',
		destination: '/:lang/:currency/local-partners',
		permanent: true,
	},
	{ source: '/partnership', destination: '/en/usd/local-partners', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/me',
		destination: '/:lang/:currency/dashboard/profile',
		permanent: true,
	},
	{ source: '/me', destination: '/en/usd/dashboard/profile', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/explainer-video',
		destination: '/:lang/:currency/videos',
		permanent: true,
	},
	{ source: '/explainer-video', destination: '/en/usd/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/money-route-video',
		destination: '/:lang/:currency/videos',
		permanent: true,
	},
	{ source: '/money-route-video', destination: '/en/usd/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/testimonial-video',
		destination: '/:lang/:currency/videos',
		permanent: true,
	},
	{ source: '/testimonial-video', destination: '/en/usd/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/legal/privacy',
		destination: '/:lang/:currency/legal',
		permanent: true,
	},
	{ source: '/legal/privacy', destination: '/en/usd/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/legal/donations',
		destination: '/:lang/:currency/legal',
		permanent: true,
	},
	{ source: '/legal/donations', destination: '/en/usd/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/legal/fundraisers',
		destination: '/:lang/:currency/legal',
		permanent: true,
	},
	{ source: '/legal/fundraisers', destination: '/en/usd/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/legal/site-use',
		destination: '/:lang/:currency/legal',
		permanent: true,
	},
	{ source: '/legal/site-use', destination: '/en/usd/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/transparency/evidence',
		destination: '/:lang/:currency/transparency',
		permanent: true,
	},
	{ source: '/transparency/evidence', destination: '/en/usd/transparency', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/transparency/reporting',
		destination: '/:lang/:currency/transparency',
		permanent: true,
	},
	{ source: '/transparency/reporting', destination: '/en/usd/transparency', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/transparency/recipient-selection',
		destination: '/:lang/:currency/recipient-selection',
		permanent: true,
	},
	{ source: '/transparency/recipient-selection', destination: '/en/usd/recipient-selection', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/journal/tag/direct-cash',
		destination: '/:lang/:currency/journal?tag=direct-cash',
		permanent: true,
	},
	{ source: '/journal/tag/direct-cash', destination: '/en/usd/journal?tag=direct-cash', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/journal/tag/media-coverage',
		destination: '/:lang/:currency/journal?tag=media-coverage',
		permanent: true,
	},
	{ source: '/journal/tag/media-coverage', destination: '/en/usd/journal?tag=media-coverage', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/journal/tag/universal-basic-income',
		destination: '/:lang/:currency/journal?tag=universal-basic-income',
		permanent: true,
	},
	{
		source: '/journal/tag/universal-basic-income',
		destination: '/en/usd/journal?tag=universal-basic-income',
		permanent: true,
	},
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/journal/tag/poverty',
		destination: '/:lang/:currency/journal?tag=poverty',
		permanent: true,
	},
	{ source: '/journal/tag/poverty', destination: '/en/usd/journal?tag=poverty', permanent: true },
	{ source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/donate', destination: '/:lang/:currency', permanent: true },
	{ source: '/donate', destination: '/en/usd', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/donate/individual',
		destination: '/:lang/:currency',
		permanent: true,
	},
	{ source: '/donate/individual', destination: '/en/usd', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/donate/one-time',
		destination: '/:lang/:currency',
		permanent: true,
	},
	{ source: '/donate/one-time', destination: '/en/usd', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:currency(chf|eur|usd)/donate/monthly',
		destination: '/:lang/:currency',
		permanent: true,
	},
	{ source: '/donate/monthly', destination: '/en/usd', permanent: true },
	{ source: '/twint', destination: '/en/usd', permanent: true },
	{ source: '/erklaert', destination: '/en/usd/videos', permanent: true },
	{ source: '/explained', destination: '/en/usd/videos', permanent: true },
	{ source: '/privacy', destination: '/en/usd/legal', permanent: true },
	{ source: '/terms-and-conditions', destination: '/en/usd/legal', permanent: true },
	{ source: '/terms-of-use', destination: '/en/usd/legal', permanent: true },
	{ source: '/press', destination: '/en/usd/journal?tag=media-coverage', permanent: true },
	{ source: '/newsletter-archive', destination: '/en/usd/journal?tag=newsletter', permanent: true },
	{ source: '/github', destination: 'https://github.com/socialincome-san/public', permanent: true },
	{ source: '/thinkcell', destination: 'https://socialincome.webdisc.ch/', permanent: true },
	{
		source: '/world-poverty-statistics-2022',
		destination: '/en/usd/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/world-poverty-statistics-2023',
		destination: '/en/usd/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/world-poverty-statistics-2024',
		destination: '/en/usd/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/how-to-reduce-income-inequality',
		destination: '/en/usd/journal/how-to-reduce-income-inequality',
		permanent: true,
	},
	{ source: '/what-is-poverty', destination: '/en/usd/journal/what-is-poverty', permanent: true },
	{ source: '/ismatu', destination: '/de/chf/campaigns/ismatu', permanent: true },
];

export const getRedirects = () => Promise.resolve(redirects);
