import type { NextConfig } from 'next';

type Redirects = Awaited<ReturnType<NonNullable<NextConfig['redirects']>>>;

const redirects: Redirects = [
	{ source: '/:lang(en|de|fr|it)/:region(int|ch)/about-us', destination: '/:lang/:region/mission', permanent: true },
	{ source: '/about-us', destination: '/en/int/mission', permanent: true },
	{ source: '/:lang(en|de|fr|it)/:region(int|ch)/app', destination: '/:lang/:region/mobile-app', permanent: true },
	{ source: '/app', destination: '/en/int/mobile-app', permanent: true },
	{ source: '/:lang(en|de|fr|it)/:region(int|ch)/bank', destination: '/:lang/:region/mobile-money', permanent: true },
	{ source: '/bank', destination: '/en/int/mobile-money', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/arts',
		destination: '/:lang/:region/programs/ubi-for-artists',
		permanent: true,
	},
	{ source: '/arts', destination: '/en/int/programs/ubi-for-artists', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/books',
		destination: '/:lang/:region/journal/recommended-reading',
		permanent: true,
	},
	{ source: '/books', destination: '/en/int/journal/recommended-reading', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/partners',
		destination: '/:lang/:region/local-partners',
		permanent: true,
	},
	{ source: '/partners', destination: '/en/int/local-partners', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/partnership',
		destination: '/:lang/:region/local-partners',
		permanent: true,
	},
	{ source: '/partnership', destination: '/en/int/local-partners', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/me',
		destination: '/:lang/:region/dashboard/profile',
		permanent: true,
	},
	{ source: '/me', destination: '/en/int/dashboard/profile', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/explainer-video',
		destination: '/:lang/:region/videos',
		permanent: true,
	},
	{ source: '/explainer-video', destination: '/en/int/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/money-route-video',
		destination: '/:lang/:region/videos',
		permanent: true,
	},
	{ source: '/money-route-video', destination: '/en/int/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/testimonial-video',
		destination: '/:lang/:region/videos',
		permanent: true,
	},
	{ source: '/testimonial-video', destination: '/en/int/videos', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/legal/privacy',
		destination: '/:lang/:region/legal',
		permanent: true,
	},
	{ source: '/legal/privacy', destination: '/en/int/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/legal/donations',
		destination: '/:lang/:region/legal',
		permanent: true,
	},
	{ source: '/legal/donations', destination: '/en/int/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/legal/fundraisers',
		destination: '/:lang/:region/legal',
		permanent: true,
	},
	{ source: '/legal/fundraisers', destination: '/en/int/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/legal/site-use',
		destination: '/:lang/:region/legal',
		permanent: true,
	},
	{ source: '/legal/site-use', destination: '/en/int/legal', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/transparency/evidence',
		destination: '/:lang/:region/transparency',
		permanent: true,
	},
	{ source: '/transparency/evidence', destination: '/en/int/transparency', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/transparency/reporting',
		destination: '/:lang/:region/transparency',
		permanent: true,
	},
	{ source: '/transparency/reporting', destination: '/en/int/transparency', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/transparency/recipient-selection',
		destination: '/:lang/:region/recipient-selection',
		permanent: true,
	},
	{ source: '/transparency/recipient-selection', destination: '/en/int/recipient-selection', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/journal/tag/direct-cash',
		destination: '/:lang/:region/journal?tag=direct-cash',
		permanent: true,
	},
	{ source: '/journal/tag/direct-cash', destination: '/en/int/journal?tag=direct-cash', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/journal/tag/media-coverage',
		destination: '/:lang/:region/journal?tag=media-coverage',
		permanent: true,
	},
	{ source: '/journal/tag/media-coverage', destination: '/en/int/journal?tag=media-coverage', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/journal/tag/universal-basic-income',
		destination: '/:lang/:region/journal?tag=universal-basic-income',
		permanent: true,
	},
	{
		source: '/journal/tag/universal-basic-income',
		destination: '/en/int/journal?tag=universal-basic-income',
		permanent: true,
	},
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/journal/tag/poverty',
		destination: '/:lang/:region/journal?tag=poverty',
		permanent: true,
	},
	{ source: '/journal/tag/poverty', destination: '/en/int/journal?tag=poverty', permanent: true },
	{ source: '/:lang(en|de|fr|it)/:region(int|ch)/donate', destination: '/:lang/:region', permanent: true },
	{ source: '/donate', destination: '/en/int', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/donate/individual',
		destination: '/:lang/:region',
		permanent: true,
	},
	{ source: '/donate/individual', destination: '/en/int', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/donate/one-time',
		destination: '/:lang/:region',
		permanent: true,
	},
	{ source: '/donate/one-time', destination: '/en/int', permanent: true },
	{
		source: '/:lang(en|de|fr|it)/:region(int|ch)/donate/monthly',
		destination: '/:lang/:region',
		permanent: true,
	},
	{ source: '/donate/monthly', destination: '/en/int', permanent: true },
	{ source: '/twint', destination: '/en/int', permanent: true },
	{ source: '/erklaert', destination: '/en/int/videos', permanent: true },
	{ source: '/explained', destination: '/en/int/videos', permanent: true },
	{ source: '/privacy', destination: '/en/int/legal', permanent: true },
	{ source: '/terms-and-conditions', destination: '/en/int/legal', permanent: true },
	{ source: '/terms-of-use', destination: '/en/int/legal', permanent: true },
	{ source: '/press', destination: '/en/int/journal?tag=media-coverage', permanent: true },
	{ source: '/newsletter-archive', destination: '/en/int/journal?tag=newsletter', permanent: true },
	{ source: '/github', destination: 'https://github.com/socialincome-san/public', permanent: true },
	{ source: '/thinkcell', destination: 'https://socialincome.webdisc.ch/', permanent: true },
	{
		source: '/world-poverty-statistics-2022',
		destination: '/en/int/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/world-poverty-statistics-2023',
		destination: '/en/int/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/world-poverty-statistics-2024',
		destination: '/en/int/journal/world-poverty-statistics-2024',
		permanent: true,
	},
	{
		source: '/how-to-reduce-income-inequality',
		destination: '/en/int/journal/how-to-reduce-income-inequality',
		permanent: true,
	},
	{ source: '/what-is-poverty', destination: '/en/int/journal/what-is-poverty', permanent: true },
	{ source: '/ismatu', destination: '/de/ch/campaigns/ismatu', permanent: true },
];

export const getRedirects = () => Promise.resolve(redirects);
