name: Admin - build and deploy
on:
  pull_request:
    paths-ignore:
      - "admin/**"
      - "shared/src/**"
      - ".github/workflows/admin.yml"
  push:
    branches:
      - main
    paths-ignore:
      - "admin/**"
      - "shared/src/**"
      - ".github/workflows/admin.yml"

jobs:
  test_deploy:
    runs-on: ubuntu-latest
    steps:
      - run: 'echo "No changes" '
