name: Aikido Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aikido-local-scan-repo:
    name: "🛡️ Aikido Security Scan"
    runs-on: ubuntu-latest

    container:
      image: aikidosecurity/local-scanner:latest@sha256:19354b564b845c2daf194f0e5b34d3c11d47902e4f2b4519373d51c37cd3ee05

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Run scan
        run: |
          aikido-local-scanner scan ./ \
            --apikey ${{ secrets.AIKIDO_API_KEY }} \
            --repositoryname socialincome-public \
            --branchname main
