name: Aikido Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aikido-local-scan-repo:
    name: "🛡️ Aikido Security Scan"
    runs-on: ubuntu-latest

    container:
      image: aikidosecurity/local-scanner:latest@sha256:a0ae4fe91fd3e9f605d884f2e9407c96b766bdd0fc6cfdfdbccb3b8f2f96636e

    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          fetch-depth: 0

      - name: Run scan
        run: |
          aikido-local-scanner scan ./ \
            --apikey ${{ secrets.AIKIDO_API_KEY }} \
            --repositoryname socialincome-public \
            --branchname main
