name: Aikido Scan

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  aikido-local-scan-repo:
    name: "🛡️ Aikido Security Scan"
    runs-on: ubuntu-latest

    container:
      image: aikidosecurity/local-scanner:latest@sha256:804590835f9c5600c78ea56341781bed7c5c56a59b07f1234294cf3e7bee2548

    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
        with:
          fetch-depth: 0

      - name: Run scan
        run: |
          aikido-local-scanner scan ./ \
            --apikey ${{ secrets.AIKIDO_API_KEY }} \
            --repositoryname socialincome-public \
            --branchname main
