name: Backend Functions - PR Run
on:
  pull_request:
    paths:
      - "backend/**"
jobs:
  build_and_preview:
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Install & Setup Firebase Emulator Suite
        run: |
          yarn global add firebase-tools && \
          firebase setup:emulators:firestore && \
          firebase setup:emulators:ui

      - name: Install Dependencies
        working-directory: backend/functions
        run: yarn install

      - name: Add secrets to env file
        working-directory: backend/functions
        run: |
          echo TEST=${{ secrets.BACKEND_TEST }} >> .env

      - name: Deploy to Firebase
        run: firebase deploy --token ${{ secrets.FIREBASE_TOKEN }}
