name: Prettify Code
on: pull_request

jobs:
  prettify:
    name: Prettify
    runs-on: ubuntu-latest
    # This action only works on the original repository, not on forks
    if: "${{ github.event.pull_request.head.repo.full_name == github.repository }}"
    steps:
      - name: Checkout repository
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6
        with:
          # Make sure the actual branch is checked out when running on pull requests, required for prettify
          ref: ${{ github.head_ref }}
          token: ${{ secrets.WORKFLOW_TOKEN }}

      - name: Initialize repository
        uses: ./.github/workflows/actions/init
        with:
          installDependencies: "true"

      - name: Prettify code
        working-directory: website
        run: npx prettier --write . --config prettier.config.cjs --ignore-path .prettierignore

      - name: Commit prettified code
        uses: stefanzweifel/git-auto-commit-action@04702edda442b2e678b25b537cec683a1493fcb9 # v7
        with:
          commit_message: "style: prettify code [skip ci]"
          branch: ${{ github.head_ref }}
          commit_user_name: github-actions
          commit_user_email: actions@github.com
